runtime: php74

runtime_config:
  document_root: public

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:ne5h3dx1mbfk+oN3HcBf3NtlR8KuMVFeEz04RJkEYj4=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie  
  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  APP_CONFIG_CACHE: /tmp/config.php
  APP_ROUTES_CACHE: /tmp/routes.php
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: warker
  DB_USERNAME: root
  DB_PASSWORD: 4132
  DB_SOCKET: "/cloudsql/bid-constru-civil:southamerica-east1:warker"